export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILED = "GET_LOCATIONS_FAILED";

// export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
// export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

// export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
// export const DELETE_BOOK_FAILED = "DELETE_BOOK_FAILED";
