export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

export const DELETE_BOOK_PENDING = "DELETE_BOOK_PENDING";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILED = "DELETE_BOOK_FAILED";

export const EDIT_BOOK_PENDING = "EDIT_BOOK_PENDING";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILED = "EDIT_BOOK_FAILED";
